version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: webtech
      POSTGRES_USER: webuser
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    image: php:8.1-fpm
    volumes:
      - ./backend:/var/www/backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  adminer:
    image: adminer
    ports:
      - "8080:8080"
